SEPDotNetCore.ChartWebApp/Models/ApexChartPieChartModel.cs
namespace SEPDotNetCore.ChartWebApp.Models
{
    public class ApexChartPieChartModel
    {
        public int[] Series { get; set; }
        public string[] Labels { get; set; }
    }

    public class ApexChartMixedChartModel
    {
        public List<SeriesData> Series { get; set; }
        public string[] Labels { get; set; }
    }

    public class SeriesData
    {
        public string Name { get; set; }
        public string Type { get; set; }
        public int[] Data { get; set; }
    }

    public class DonutChartModel
    {
        public List<string> Labels { get; set; }
        public List<int> Series { get; set; }
    }

    public class ColumnChartModel
    {
        public List<string> Brands { get; set; }
        public List<int> Sales { get; set; }
    }
    public class BorderChartModel
    {
        public List<string> Labels { get; set; }
        public List<int> Dataset1 { get; set; }
        public List<int> Dataset2 { get; set; }
    }

    public class RadarChartModel
    {
        public List<string> Labels { get; set; }
        public List<int> Dataset1 { get; set; }
        public List<int> Dataset2 { get; set; }
    }

    public class BoxWhiskerChartModel
    {
        public List<string> Labels { get; set; }
        public List<List<int>> DataPoints { get; set; }
    }

    public class LineChartModel
    {
        public List<DateTime> Dates { get; set; } 
        public List<double> Prices { get; set; }  
        public List<string> IndexLabels { get; set; } 
        public List<string> MarkerTypes { get; set; }  
        public List<string> MarkerColors { get; set; } 
    }
}

SEPDotNetCore.ChartWebApp/Models/ErrorViewModel.cs
namespace SEPDotNetCore.ChartWebApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SEPDotNetCore.ChartWebApp/Controllers/ApexChartController.cs
using Microsoft.AspNetCore.Mvc;
using SEPDotNetCore.ChartWebApp.Models;

namespace SEPDotNetCore.ChartWebApp.Controllers
{
    public class ApexChartController : Controller
    {
        public IActionResult PieChart()
        {
            ApexChartPieChartModel model = new ApexChartPieChartModel();
            model.Series = new int[] { 44, 55, 13, 43, 22 };
            model.Labels = new string[] { "Team A", "Team B", "Team C", "Team D", "Team E" };
            return View(model);
        }

        public IActionResult MixedChart()
        {
            var model = new ApexChartMixedChartModel
            {
                Series = new List<SeriesData>
            {
                new SeriesData
                {
                    Name = "TEAM A",
                    Type = "column",
                    Data = new int[] { 23, 11, 22, 27, 13, 22, 37, 21, 44, 22, 30 }
                },
                new SeriesData
                {
                    Name = "TEAM B",
                    Type = "area",
                    Data = new int[] { 44, 55, 41, 67, 22, 43, 21, 41, 56, 27, 43 }
                },
                new SeriesData
                {
                    Name = "TEAM C",
                    Type = "line",
                    Data = new int[] { 30, 25, 36, 30, 45, 35, 64, 52, 59, 36, 39 }
                }
            },
                Labels = new string[] { "01/01/2003", "02/01/2003", "03/01/2003", "04/01/2003", "05/01/2003", "06/01/2003", "07/01/2003", "08/01/2003", "09/01/2003", "10/01/2003", "11/01/2003" }
            };

            return View(model);
        }

        public IActionResult DonutChart()
        {         
            var model = new DonutChartModel
            {
                Labels = new List<string> { "Norway", "Germany", "USA", "Sweden", "Netherlands", "ROC", "Austria", "Canada", "Japan" },
                Series = new List<int> { 16, 12, 8, 8, 8, 6, 7, 4, 3 }
            };

           
            return View(model);
        }

        public IActionResult ColumnChart()
        {
         
            var model = new ColumnChartModel
            {
                Brands = new List<string> { "Toyota", "Volkswagen", "Volvo", "Tesla", "Hyundai", "MG", "Skoda", "BMW", "Ford", "Nissan" },
                Sales = new List<int> { 1795, 1242, 1074, 832, 593, 509, 471, 442, 385, 371 }
            };
            return View(model);
        }

        public IActionResult BorderChart()
        {
          
            var model = new BorderChartModel
            {
                Labels = new List<string> { "January", "February", "March", "April", "May", "June", "July" },
                Dataset1 = new List<int> { 65, 59, 80, 81, 56, 55, 40 }, 
                Dataset2 = new List<int> { 28, 48, 40, 19, 86, 27, 90 }  
            };

            return View(model);
        }

        public IActionResult RadarChart()
        {
           
            var model = new RadarChartModel
            {
                Labels = new List<string> { "Eating", "Drinking", "Sleeping", "Designing", "Coding", "Cycling", "Running" },
                Dataset1 = new List<int> { 65, 59, 90, 81, 56, 55, 40 },  
                Dataset2 = new List<int> { 28, 48, 40, 19, 96, 27, 100 }  
            };

            return View(model);
        }

        public IActionResult BoxWhiskerChart()
        {
         
            var model = new BoxWhiskerChartModel
            {
                Labels = new List<string> { "Registered Nurse", "Web Developer", "System Analyst", "Application Engineer", "Aerospace Engineer", "Dentist" },
                DataPoints = new List<List<int>>
            {
                new List<int> { 46360, 55320, 82490, 101650, 71000 },
                new List<int> { 83133, 91830, 115828, 128982, 101381 },
                new List<int> { 51910, 60143, 115056, 135450, 85800 },
                new List<int> { 63364, 71653, 91120, 100556, 80757 },
                new List<int> { 82725, 94361, 118683, 129191, 107142 },
                new List<int> { 116777, 131082, 171679, 194336, 146794 }
            }
            };

          
            return View(model);
        }

        public IActionResult LineChart()
        {
          
            var model = new LineChartModel
            {
                Dates = new List<DateTime>
            {
                new DateTime(2016, 1, 1),
                new DateTime(2016, 2, 1),
                new DateTime(2016, 3, 1),
                new DateTime(2016, 4, 1),
                new DateTime(2016, 5, 1),
                new DateTime(2016, 6, 1),
                new DateTime(2016, 7, 1),
                new DateTime(2016, 8, 1),
                new DateTime(2016, 9, 1),
                new DateTime(2016, 10, 1),
                new DateTime(2016, 11, 1),
                new DateTime(2016, 12, 1)
            },
                Prices = new List<double> { 61, 71, 55, 50, 65, 85, 68, 28, 34, 24, 44, 34 },
                IndexLabels = new List<string> { "gain", "gain", "loss", "loss", "gain", "gain", "loss", "loss", "gain", "loss", "gain", "loss" },
                MarkerTypes = new List<string> { "triangle", "triangle", "cross", "cross", "triangle", "triangle", "cross", "cross", "triangle", "cross", "triangle", "cross" },
                MarkerColors = new List<string> { "#6B8E23", "#6B8E23", "tomato", "tomato", "#6B8E23", "#6B8E23", "tomato", "tomato", "#6B8E23", "tomato", "#6B8E23", "tomato" }
            };

           
            return View(model);
        }
    }       
}

SEPDotNetCore.ChartWebApp/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using SEPDotNetCore.ChartWebApp.Models;

namespace SEPDotNetCore.ChartWebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SEPDotNetCore.ChartWebApp/Views/ApexChart/BorderChart.cshtml
@model BorderChartModel
@{
 
    var labels = Model.Labels;
    var dataset1 = Model.Dataset1;
    var dataset2 = Model.Dataset2;
}

<div style="width: 75%; margin: auto;">
    <canvas id="borderChart"></canvas>
</div>

@section Scripts {
    <script>
       
        const labels = @Html.Raw(Json.Serialize(labels));
        const dataset1 = @Html.Raw(Json.Serialize(dataset1));
        const dataset2 = @Html.Raw(Json.Serialize(dataset2));

        
        const ctx = document.getElementById('borderChart').getContext('2d');
        const borderChart = new Chart(ctx, {
            type: 'bar', 
            data: {
                labels: labels,
                datasets: [
                    {
                        label: 'Dataset 1',
                        data: dataset1,
                        borderColor: 'rgba(255, 99, 132, 1)', 
                        backgroundColor: 'rgba(255, 99, 132, 0.2)', 
                        borderWidth: 3 
                    },
                    {
                        label: 'Dataset 2',
                        data: dataset2,
                        borderColor: 'rgba(54, 162, 235, 1)', 
                        backgroundColor: 'rgba(54, 162, 235, 0.2)', 
                        borderWidth: 3 
                    }
                ]
            },
            options: {
                scales: {
                    y: {
                        beginAtZero: true
                    }
                }
            }
        });
    </script>
}

SEPDotNetCore.ChartWebApp/Views/ApexChart/BoxWhiskerChart.cshtml
@model BoxWhiskerChartModel
@{
    var labels = Model.Labels;
    var dataPoints = Model.DataPoints;
}


    <div id="chartContainer" style="height: 370px; width: 100%;"></div>

@section scripts{
	 <script>
        window.onload = function () {
          
            const labels = @Html.Raw(Json.Serialize(labels));
            const dataPoints = @Html.Raw(Json.Serialize(dataPoints));

            
            const chartData = labels.map((label, index) => ({
                label: label,
                y: dataPoints[index]
            }));

            var chart = new CanvasJS.Chart("chartContainer", {
                animationEnabled: true,
                title: {
                    text: "Annual Salary Range - USA"
                },
                axisY: {
                    title: "Annual Salary (in USD)",
                    prefix: "$",
                    interval: 40000
                },
                data: [{
                    type: "boxAndWhisker",
                    upperBoxColor: "#FFC28D",
                    lowerBoxColor: "#9ECCB8",
                    color: "black",
                    yValueFormatString: "$#,##0",
                    dataPoints: chartData
                }]
            });
            chart.render();
        }
    </script>

}

   

SEPDotNetCore.ChartWebApp/Views/ApexChart/ColumnChart.cshtml
@model ColumnChartModel
@{
    var brands = Model.Brands;
    var sales = Model.Sales;
}


    <div id="chart" style="min-width: 310px; height: 400px; margin: 0 auto"></div>

 
    <div id="sliders" style="margin-top: 20px;">
        <label for="alpha">Alpha Angle:</label>
        <input id="alpha" type="range" min="0" max="45" value="15" />
        <span id="alpha-value">15</span><br />

        <label for="beta">Beta Angle:</label>
        <input id="beta" type="range" min="0" max="45" value="15" />
        <span id="beta-value">15</span><br />

        <label for="depth">Depth:</label>
        <input id="depth" type="range" min="20" max="100" value="50" />
        <span id="depth-value">50</span><br />
    </div>

    @section scripts {
      

        <script>
            const brands = @Html.Raw(Json.Serialize(brands));
            const sales = @Html.Raw(Json.Serialize(sales));


            const chartData = brands.map((brand, index) => ({
                name: brand,
                y: sales[index]
            }));

           
            const chart = new Highcharts.Chart({
                chart: {
                    renderTo: 'chart',
                    type: 'column',
                    options3d: {
                        enabled: true,
                        alpha: 15,
                        beta: 15,
                        depth: 50,
                        viewDistance: 25
                    }
                },
                xAxis: {
                    type: 'category'
                },
                yAxis: {
                    title: {
                        enabled: false
                    }
                },
                tooltip: {
                    headerFormat: '<b>{point.key}</b><br>',
                    pointFormat: 'Cars sold: {point.y}'
                },
                title: {
                    text: 'Sold passenger cars in Norway by brand, May 2024'
                },
                subtitle: {
                    text: 'Source: ' +
                        '<a href="https://ofv.no/registreringsstatistikk"' +
                        'target="_blank">OFV</a>'
                },
                legend: {
                    enabled: false
                },
                plotOptions: {
                    column: {
                        depth: 25
                    }
                },
                series: [{
                    data: chartData,
                    colorByPoint: true
                }]
            });

            function showValues() {
                document.getElementById('alpha-value').innerHTML = chart.options.chart.options3d.alpha;
                document.getElementById('beta-value').innerHTML = chart.options.chart.options3d.beta;
                document.getElementById('depth-value').innerHTML = chart.options.chart.options3d.depth;
            }

            document.querySelectorAll('#sliders input').forEach(input => {
                input.addEventListener('input', e => {
                    chart.options.chart.options3d[e.target.id] = parseFloat(e.target.value);
                    showValues();
                    chart.redraw(false);
                });
            });

            showValues();
        </script>
    }

SEPDotNetCore.ChartWebApp/Views/ApexChart/DonutChart.cshtml
@model DonutChartModel
@{
    var labels = Model.Labels;
    var series = Model.Series;
}


   <div id="chart" style="min-width: 310px; height: 400px; margin: 0 auto"></div>

@section scripts {
      
   <script>
          
            const labels = @Html.Raw(Json.Serialize(labels));
            const series = @Html.Raw(Json.Serialize(series));

          
            const chartData = labels.map((label, index) => ({
                name: label,
                y: series[index]
            }));

           
            Highcharts.chart('chart', {
                chart: {
                    type: 'pie',
                    options3d: {
                        enabled: true,
                        alpha: 45 
                    }
                },
                title: {
                    text: 'Beijing 2022 Gold Medals by Country'
                },
                subtitle: {
                    text: '3D Donut in Highcharts'
                },
                plotOptions: {
                    pie: {
                        innerSize: 100, 
                        depth: 45 
                    }
                },
                series: [{
                    name: 'Medals',
                    data: chartData
                }],
                tooltip: {
                    pointFormat: '{point.name}: <b>{point.y} gold medals</b>'
                },
                accessibility: {
                    point: {
                        valueSuffix: 'gold medals'
                    }
                }
            });
</script>
}

SEPDotNetCore.ChartWebApp/Views/ApexChart/LineChart.cshtml
@model LineChartModel
@{
    var dates = Model.Dates;
    var prices = Model.Prices;
    var indexLabels = Model.IndexLabels;
    var markerTypes = Model.MarkerTypes;
    var markerColors = Model.MarkerColors;
}
 
    <div id="chartContainer" style="height: 370px; width: 100%;"></div>

    @section scripts {
       
        <script>
            window.onload = function () {
                 
                const dates = @Html.Raw(Json.Serialize(dates));
                const prices = @Html.Raw(Json.Serialize(prices));
                const indexLabels = @Html.Raw(Json.Serialize(indexLabels));
                const markerTypes = @Html.Raw(Json.Serialize(markerTypes));
                const markerColors = @Html.Raw(Json.Serialize(markerColors));

               
                const dataPoints = dates.map((date, index) => ({
                    x: new Date(date),
                    y: prices[index],
                    indexLabel: indexLabels[index],
                    markerType: markerTypes[index],
                    markerColor: markerColors[index]
                }));

                
                var chart = new CanvasJS.Chart("chartContainer", {
                    theme: "light2",  
                    animationEnabled: true,
                    title: {
                        text: "Share Value - 2016"
                    },
                    axisX: {
                        interval: 1,
                        intervalType: "month",
                        valueFormatString: "MMM"
                    },
                    axisY: {
                        title: "Price (in USD)",
                        includeZero: true,
                        valueFormatString: "$#0"
                    },
                    data: [{
                        type: "line",
                        markerSize: 12,
                        xValueFormatString: "MMM, YYYY",
                        yValueFormatString: "$###.#",
                        dataPoints: dataPoints
                    }]
                });
                chart.render();
            }
        </script>
    }
 

SEPDotNetCore.ChartWebApp/Views/ApexChart/MixedChart.cshtml
@model ApexChartMixedChartModel

@{
    var series = Model.Series;
    var labels = Model.Labels;
}

<div id="chart"></div>

@section scripts {
    <script>
        const series = @Html.Raw(JsonConvert.SerializeObject(series));
        const labels = @Html.Raw(JsonConvert.SerializeObject(labels));

        var options = {
            series: series,
            chart: {
                height: 350,
                type: 'line',
                stacked: false,
            },
            stroke: {
                width: [0, 2, 5],
                curve: 'smooth'
            },
            plotOptions: {
                bar: {
                    columnWidth: '50%'
                }
            },
            fill: {
                opacity: [0.85, 0.25, 1],
                gradient: {
                    inverseColors: false,
                    shade: 'light',
                    type: "vertical",
                    opacityFrom: 0.85,
                    opacityTo: 0.55,
                    stops: [0, 100, 100, 100]
                }
            },
            labels: labels,
            markers: {
                size: 0
            },
            xaxis: {
                type: 'datetime'
            },
            yaxis: {
                title: {
                    text: 'Points',
                }
            },
            tooltip: {
                shared: true,
                intersect: false,
                y: {
                    formatter: function (y) {
                        if (typeof y !== "undefined") {
                            return y.toFixed(0) + " points";
                        }
                        return y;
                    }
                }
            }
        };

        var chart = new ApexCharts(document.querySelector("#chart"), options);
        chart.render();
    </script>
}

SEPDotNetCore.ChartWebApp/Views/ApexChart/PieChart.cshtml
@model ApexChartPieChartModel
@{
	int[] _series = Model.Series;
	string[] _labels = Model.Labels;
}


<div id="chart"></div>

@section scripts{

    <script>

		const _series = @Html.Raw(JsonConvert.SerializeObject(_series));
		const _labels = @Html.Raw(JsonConvert.SerializeObject(_labels));

        var options = {
              series: _series,
              chart: {
              width: 380,
              type: 'pie',
            },
			labels:_labels,
            responsive: [{
              breakpoint: 480,
              options: {
                chart: {
                  width: 200
                },
                legend: {
                  position: 'bottom'
                }
              }
            }]
            };

            var chart = new ApexCharts(document.querySelector("#chart"), options);
            chart.render();

    </script>
}

SEPDotNetCore.ChartWebApp/Views/ApexChart/RadarChart.cshtml
@model RadarChartModel
@{
    var labels = Model.Labels;
    var dataset1 = Model.Dataset1;
    var dataset2 = Model.Dataset2;
}


    <div style="width: 75%; margin: auto;">
        <canvas id="radarChart"></canvas>
    </div>

@section scripts {
    <script>

        const labels = @Html.Raw(Json.Serialize(labels));
        const dataset1 = @Html.Raw(Json.Serialize(dataset1));
        const dataset2 = @Html.Raw(Json.Serialize(dataset2));

        const ctx = document.getElementById('radarChart').getContext('2d');
        const radarChart = new Chart(ctx, {
            type: 'radar',
            data: {
                labels: labels,
                datasets: [
                    {
                        label: 'Dataset 1',
                        data: dataset1,
                        borderColor: 'rgba(255, 99, 132, 1)',
                        backgroundColor: 'rgba(255, 99, 132, 0.2)',
                        borderWidth: 2
                    },
                    {
                        label: 'Dataset 2',
                        data: dataset2,
                        borderColor: 'rgba(54, 162, 235, 1)',
                        backgroundColor: 'rgba(54, 162, 235, 0.2)',
                        borderWidth: 2
                    }
                ]
            },
            options: {
                scales: {
                    r: {
                        angleLines: {
                            display: true
                        },
                        suggestedMin: 0,
                        suggestedMax: 100
                    }
                }
            }
        });
    </script>
}

 

SEPDotNetCore.ChartWebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

SEPDotNetCore.ChartWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SEPDotNetCore.ChartWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SEPDotNetCore.ChartWebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SEPDotNetCore.ChartWebApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ApexChart" asp-action="PieChart">Pie Chart</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ApexChart" asp-action="MixedChart">Mixed Chart</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ApexChart" asp-action="DonutChart">Donut Chart</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ApexChart" asp-action="ColumnChart">Column Chart</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ApexChart" asp-action="BorderChart">Border Chart</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ApexChart" asp-action="RadarChart">Radar Chart</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ApexChart" asp-action="BoxWhiskerChart">BoxWhisker Chart</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ApexChart" asp-action="LineChart">Line Chart</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - SEPDotNetCore.ChartWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>

    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/highcharts-3d.js"></script>  
    <script src="https://code.highcharts.com/modules/exporting.js"></script> 
    <script src="https://code.highcharts.com/modules/export-data.js"></script> 
    <script src="https://code.highcharts.com/modules/accessibility.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

   <script src="https://cdn.canvasjs.com/ga/canvasjs.min.js"></script>

    @await RenderSectionAsync("scripts", required: false)
</body>
</html>